apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-todo-client-deployment
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: akkyou/client:latest
      
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client 
    
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    
    

  
 





