version: '3'
services:
  server:
    build:
      context: ./server/
    image: akkyou/server:latest
    command: "node server.js"
    
    ports:
      - "5000:5000"
    links:
      - mongo
    
  client:
    build:
      context: ./client/
    image: akkyou/client:latest
    command: "npm start"
    
    
    ports:
      - "3000:3000"
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
