apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-todo-server-deployment
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: akkyou/server:latest
        ports:
        - containerPort: 9999

---

apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 9999
    

  
 











