name: Mirror and run GitLab CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://gitlab.com/automation204/todo.git"
      env:
        GITLAB_HOSTNAME: "gitlab.com"
        GITLAB_USERNAME: "Prateek vats"
        GITLAB_PASSWORD: glpat-kWsv-7jFStYv6vWh5FhW
        GITLAB_PROJECT_ID: "37783515" 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
